%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
# ImageTopic: "/camera/color/image_raw"
ImageTopic: "/usb_cam/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  # data: [-0.11548,-0.993211,0.0140318,-0.0232232,
  #        -0.104532,-0.00189647,-0.99452,-0.291641,
  #        0.987794,-0.116314,-0.103603,0.151607,
  #        0,0,0,1]
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 45
Plane.normal_theta_max: 135
Plane.max_size: 5 #8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06
