%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
# ImageTopic: "/camera/color/image_raw"
ImageTopic: "/usb_cam/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
  # date: [0.9659, 0.0,   0.2588, 0.0,
  #        0.0,    1.0,   0.0,    0.0,
  #        -0.2588,0.0,   0.9659, 0.0,
  #        0.0,    0.0,   0.0,    1.0]
#   date: [0.0552885,-0.997888,0.0341032,-0.015903
# -0.031057,-0.0358577,-0.998874,0.00144097
# 0.997987,0.0541671,-0.0329739,-0.470853
# 0,0,0,1]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.5
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 45
Plane.normal_theta_max: 135
Plane.max_size: 5 #8
Ransac.dis_threshold: 0.02
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06
